language: node_js

node_js:
  - "10"

cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.sonar/cache

addons:
  sonarcloud:
    organization: "javierbrea"
    token:
      secure: "$SONAR_TOKEN"
    branch:
      name: "$TRAVIS_CURRENT_BRANCH"

script:
  - npm run lint
  - npm run test-ci
  - npm run coveralls
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=${SONAR_TOKEN}; fi'

deploy:
  provider: npm
  email: "javier.brea@gmail.com"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
  skip_cleanup: true
